services:
  web: 
    build:
      context: .
    restart: always
    ports: 
      - '8000:8000'
    networks:
      - scm-net
    volumes:
      - .:/app
    depends_on:
      - cache
      - celery_worker
      - db
    env_file:
      - dev.env
      
  celery_worker:
    build:
      context: .
    restart: always
    command: /start_celery_worker
    networks:
      - scm-net
    depends_on:
      - cache
      - db
    env_file:
      - dev.env
    volumes:
      - .:/app
  
  cache:
    image: redis:7.4-alpine
    restart: always
    ports:
      - '6379:6379'
    expose:
      - '6379'
    volumes:
      - cache-volume:/data
    networks:
      - scm-net
  
  db:
    image: postgres:16-alpine
    expose:
      - 5432
    # Also expose the DB on the local machine so that tests can run on it
    ports:
      - 127.0.0.1:5432:5432
    networks:
      - scm-net
    volumes:
      - db_volume:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_PASSWORD=dev
  
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8080:80"
    networks:
      - scm-net
    volumes:
      - pgadmin_volume:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@localhost.com
      - PGADMIN_DEFAULT_PASSWORD=dev
    depends_on:
      - db

networks:
  scm-net:
    driver: bridge

volumes:
  cache-volume:
    driver: local
  db_volume:
    driver: local
  pgadmin_volume:
    driver: local

