services:
  web: 
    build:
      context: .
    restart: always
    ports: 
      - '8000:8000'
    networks:
      - scm-net
    volumes:
      - .:/app
    depends_on:
      - cache
      - celery_worker
    env_file:
      - dev.env
    environment:
      - DEFAULT_DB=sqlite
      
  celery_worker:
    build:
      context: .
    restart: always
    command: /start_celery_worker
    networks:
      - scm-net
    depends_on:
      - cache
    env_file:
      - dev.env
    volumes:
      - .:/app
    environment:
      - DEFAULT_DB=sqlite
  
  cache:
    image: redis:7.4-alpine
    restart: always
    ports:
      - '6379:6379'
    expose:
      - '6379'
    volumes:
      - cache-volume:/data
    networks:
      - scm-net
  
networks:
  scm-net:
    driver: bridge

volumes:
  cache-volume:
    driver: local