# Generated by Django 5.1.1 on 2024-09-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0003_remove_college_college_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
