# Generated by Django 5.1.1 on 2024-09-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0004_alter_college_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='college_type',
            field=models.TextField(default='ENGG'),
            preserve_default=False,
        ),
    ]
