# Generated by Django 5.1.1 on 2024-09-22 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0005_college_college_type'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='college',
            constraint=models.UniqueConstraint(fields=('code',), name='college_code_unique'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('code',), name='course_code_unique'),
        ),
    ]
