# Generated by Django 5.1.1 on 2024-09-24 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0007_college_slug'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['code'], name='college_code_index'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['code'], name='course_code_index'),
        ),
    ]
