# Generated by Django 5.1.1 on 2024-10-11 02:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0009_program_counselling_college_4aef51_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='last_choice_save_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
