# Generated by Django 5.1.1 on 2024-10-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0011_student_last_choice_save_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='choice_report_path',
            field=models.FilePathField(blank=True, null=True),
        ),
    ]
