# Generated by Django 5.1.1 on 2024-10-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0012_student_choice_report_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
    ]
