# Generated by Django 5.1.1 on 2024-10-13 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0013_alter_college_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Allotment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='counselling.program')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counselling.student')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counselling.round')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('round', 'student'), name='round_student_unique')],
            },
        ),
    ]
