# Generated by Django 5.1.1 on 2024-10-14 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0014_round_allotment'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='last_choice_report_generation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
