# Generated by Django 5.1.1 on 2024-10-15 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0015_student_last_choice_report_generation_date'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='choiceentry',
            name='student_program_unique',
        ),
        migrations.AddField(
            model_name='choiceentry',
            name='round',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='counselling.round'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='choiceentry',
            constraint=models.UniqueConstraint(fields=('student', 'program', 'round'), name='student_program_round_unique'),
        ),
        migrations.AddConstraint(
            model_name='round',
            constraint=models.UniqueConstraint(fields=('number',), name='round_number_unique'),
        ),
    ]
