# Generated by Django 5.1.1 on 2024-10-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0016_remove_choiceentry_student_program_unique_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='choice_entry_add_new_programs_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='choice_entry_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
