# Generated by Django 5.1.1 on 2024-10-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0018_alter_student_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='choice_report_path',
            field=models.FilePathField(blank=True, default='', null=True),
        ),
    ]
