# Generated by Django 5.1.1 on 2024-10-15 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0019_alter_student_choice_report_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='choice_report_path',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
