# Generated by Django 5.1.1 on 2024-09-22 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0006_college_college_code_unique_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
