# Generated by Django 5.1.1 on 2024-09-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0008_college_college_code_index_course_course_code_index'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['college', 'course'], name='counselling_college_4aef51_idx'),
        ),
        migrations.AddIndex(
            model_name='ranklist',
            index=models.Index(fields=['short_name'], name='counselling_short_n_3cb673_idx'),
        ),
    ]
