# Generated by Django 5.1.1 on 2024-10-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0010_sitepreferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitepreferences',
            name='option_entry_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
