# Generated by Django 5.1.1 on 2024-10-08 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0011_alter_sitepreferences_option_entry_enabled'),
        ('preferences', '0003_alter_preferences_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SitePreferences',
            new_name='SitePreference',
        ),
    ]
