# Generated by Django 5.1.1 on 2024-10-08 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0012_rename_sitepreferences_sitepreference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitepreference',
            old_name='option_entry_enabled',
            new_name='choice_entry_enabled',
        ),
    ]
